language: c
compiler: gcc
addons:
  apt:
    packages:
      - doxygen
script: "make && make test"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
